### ISSUE TITLE
Winget Packages returning 404

### ISSUE THREAD

**Issue by Suleman-Elahi** [yoshiask/FluentStore#38] opened 2022-04-25 11:42 UTC
### Before you start...

- [X] Have you checked if similar issue have already been reported?

### What windows are you seeing the problem on?

Windows 11 Dev

### What OS/App version/architecture are you seeing the problem on?

[v0.2.1 Beta]

### Description

No Winget package is seems to be working.

### Steps To Reproduce

1. Open app
2. Search for a package, example 7-Zip
3. Install
4. 404 Error appears

### Expected behavior

Should install the target package.

### Relevant Assets

![image](https://user-images.githubusercontent.com/24384996/165082150-31072f4d-9626-41b0-aac4-3513d7cea527.png)

**Comment by yoshiask** [comment] 2022-04-25 22:08
This is a duplicate of #20, though the issue seems to be affecting more packages as the WinGetRun repo gets further out of sync.

**Comment by yoshiask** [comment] 2022-06-16 05:23
As of 0.3.1-beta, the WinGet source uses Winstall rather WinGetRun. This change should come with increased reliability.

**Closed by yoshiask** 2022-06-16 05:23 UTC
Labels: bug, help wanted, blocked
